# -*- coding: utf-8 -*-

import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication


class Uiconversionofnumbersystems(QWidget):
    """
    程序员计算器界面（进制转换）
    """

    def __init__(self) -> object:
        super(Uiconversionofnumbersystems, self).__init__()
        self.setObjectName("conversionOfNumberSystems")
        self.setup_ui()
        self.retranslate_ui()

    def setup_ui(self):
        """
        UI设计
        :return:
        """
        self.HEX_lineEdit = QtWidgets.QLineEdit(self)
        self.HEX_lineEdit.setGeometry(QtCore.QRect(360, 30, 631, 41))
        self.HEX_lineEdit.setObjectName("lineEdit")
        self.DEC_lineEdit = QtWidgets.QLineEdit(self)
        self.DEC_lineEdit.setGeometry(QtCore.QRect(360, 90, 631, 41))
        self.DEC_lineEdit.setObjectName("lineEdit")
        self.Bin_lineEdit = QtWidgets.QLineEdit(self)
        self.Bin_lineEdit.setGeometry(QtCore.QRect(360, 150, 631, 41))
        self.Bin_lineEdit.setObjectName("lineEdit")
        self.Otc_lineEdit = QtWidgets.QLineEdit(self)
        self.Otc_lineEdit.setGeometry(QtCore.QRect(360, 210, 631, 41))
        self.Otc_lineEdit.setObjectName("lineEdit")
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(360, 290, 631, 91))
        self.lineEdit.setObjectName("lineEdit")
        self.label_1 = QtWidgets.QLabel(self)
        self.label_1.setGeometry(QtCore.QRect(180, 290, 131, 21))
        self.label_1.setObjectName("label_1")
        self.parameter_spinBox = QtWidgets.QSpinBox(self)
        self.parameter_spinBox.setGeometry(QtCore.QRect(180, 330, 46, 22))
        self.parameter_spinBox.setObjectName("parameter_spinBox")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(260, 330, 72, 21))
        self.label_2.setObjectName("label_2")
        self.reseting_Btn = QtWidgets.QPushButton(self)
        self.reseting_Btn.setGeometry(QtCore.QRect(40, 130, 93, 51))
        self.reseting_Btn.setObjectName("btn")
        self.refresh_Btn = QtWidgets.QPushButton(self)
        self.refresh_Btn.setGeometry(QtCore.QRect(40, 40, 93, 51))
        self.refresh_Btn.setObjectName("btn")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(180, 400, 811, 291))
        self.widget.setObjectName("widget")
        self.seven_Btn = QtWidgets.QPushButton(self.widget)
        self.seven_Btn.setGeometry(QtCore.QRect(300, 10, 100, 50))
        self.seven_Btn.setObjectName("btn")
        self.eight_Btn = QtWidgets.QPushButton(self.widget)
        self.eight_Btn.setGeometry(QtCore.QRect(430, 10, 100, 50))
        self.eight_Btn.setObjectName("btn")
        self.night_Btn = QtWidgets.QPushButton(self.widget)
        self.night_Btn.setGeometry(QtCore.QRect(560, 10, 100, 50))
        self.night_Btn.setObjectName("btn")
        self.clear_Btn = QtWidgets.QPushButton(self.widget)
        self.clear_Btn.setGeometry(QtCore.QRect(690, 10, 100, 50))
        self.clear_Btn.setObjectName("btn")
        self.D_Btn = QtWidgets.QPushButton(self.widget)
        self.D_Btn.setGeometry(QtCore.QRect(150, 90, 100, 50))
        self.D_Btn.setObjectName("btn")
        self.B_Btn = QtWidgets.QPushButton(self.widget)
        self.B_Btn.setGeometry(QtCore.QRect(150, 10, 100, 50))
        self.B_Btn.setObjectName("btn")
        self.four_Btn = QtWidgets.QPushButton(self.widget)
        self.four_Btn.setGeometry(QtCore.QRect(300, 90, 100, 50))
        self.four_Btn.setObjectName("btn")
        self.five_Btn = QtWidgets.QPushButton(self.widget)
        self.five_Btn.setGeometry(QtCore.QRect(430, 90, 100, 50))
        self.five_Btn.setObjectName("btn")
        self.six_Btn = QtWidgets.QPushButton(self.widget)
        self.six_Btn.setGeometry(QtCore.QRect(560, 90, 100, 50))
        self.six_Btn.setObjectName("btn")
        self.delect_btn = QtWidgets.QPushButton(self.widget)
        self.delect_btn.setGeometry(QtCore.QRect(690, 90, 100, 50))
        self.delect_btn.setObjectName("btn")
        self.A_Btn = QtWidgets.QPushButton(self.widget)
        self.A_Btn.setGeometry(QtCore.QRect(20, 10, 100, 50))
        self.A_Btn.setObjectName("btn")
        self.C_Btn = QtWidgets.QPushButton(self.widget)
        self.C_Btn.setGeometry(QtCore.QRect(20, 90, 100, 50))
        self.C_Btn.setObjectName("btn")
        self.E_Btn = QtWidgets.QPushButton(self.widget)
        self.E_Btn.setGeometry(QtCore.QRect(20, 170, 100, 50))
        self.E_Btn.setObjectName("btn")
        self.F_Btn = QtWidgets.QPushButton(self.widget)
        self.F_Btn.setGeometry(QtCore.QRect(150, 170, 100, 50))
        self.F_Btn.setObjectName("btn")
        self.one_Btn = QtWidgets.QPushButton(self.widget)
        self.one_Btn.setGeometry(QtCore.QRect(300, 170, 100, 50))
        self.one_Btn.setObjectName("btn")
        self.two_Btn = QtWidgets.QPushButton(self.widget)
        self.two_Btn.setGeometry(QtCore.QRect(430, 170, 100, 50))
        self.two_Btn.setObjectName("btn")
        self.three_Btn = QtWidgets.QPushButton(self.widget)
        self.three_Btn.setGeometry(QtCore.QRect(560, 170, 100, 50))
        self.three_Btn.setObjectName("btn")
        self.point_Btn = QtWidgets.QPushButton(self.widget)
        self.point_Btn.setGeometry(QtCore.QRect(690, 170, 100, 50))
        self.point_Btn.setObjectName("btn")
        self.zero_Btn = QtWidgets.QPushButton(self.widget)
        self.zero_Btn.setGeometry(QtCore.QRect(20, 240, 771, 41))
        self.zero_Btn.setObjectName("btn")
        self.Hex = QtWidgets.QRadioButton(self)
        self.Hex.setGeometry(QtCore.QRect(180, 40, 131, 19))
        self.Hex.setObjectName("Hex")
        self.Dec = QtWidgets.QRadioButton(self)
        self.Dec.setGeometry(QtCore.QRect(180, 100, 131, 19))
        self.Dec.setObjectName("Dec")
        self.Bin = QtWidgets.QRadioButton(self)
        self.Bin.setGeometry(QtCore.QRect(180, 160, 131, 19))
        self.Bin.setObjectName("Bin")
        self.Otc = QtWidgets.QRadioButton(self)
        self.Otc.setGeometry(QtCore.QRect(180, 220, 141, 19))
        self.Otc.setObjectName("Otc")

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslate_ui(self):
        """
        设置信息
        :return:
        """
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("conversionOfNumberSystems", "进制转换"))
        self.label_1.setText(_translate("conversionOfNumberSystems", "自定义进制转换："))
        self.label_2.setText(_translate("conversionOfNumberSystems", "进制"))
        self.reseting_Btn.setText(_translate("conversionOfNumberSystems", "重置"))
        self.refresh_Btn.setText(_translate("conversionOfNumberSystems", "刷新"))
        self.seven_Btn.setText(_translate("conversionOfNumberSystems", "7"))
        self.eight_Btn.setText(_translate("conversionOfNumberSystems", "8"))
        self.night_Btn.setText(_translate("conversionOfNumberSystems", "9"))
        self.clear_Btn.setText(_translate("conversionOfNumberSystems", "AC"))
        self.D_Btn.setText(_translate("conversionOfNumberSystems", "D"))
        self.B_Btn.setText(_translate("conversionOfNumberSystems", "B"))
        self.four_Btn.setText(_translate("conversionOfNumberSystems", "4"))
        self.five_Btn.setText(_translate("conversionOfNumberSystems", "5"))
        self.six_Btn.setText(_translate("conversionOfNumberSystems", "6"))
        self.delect_btn.setText(_translate("conversionOfNumberSystems", "X"))
        self.A_Btn.setText(_translate("conversionOfNumberSystems", "A"))
        self.C_Btn.setText(_translate("conversionOfNumberSystems", "C"))
        self.E_Btn.setText(_translate("conversionOfNumberSystems", "E"))
        self.F_Btn.setText(_translate("conversionOfNumberSystems", "F"))
        self.one_Btn.setText(_translate("conversionOfNumberSystems", "1"))
        self.two_Btn.setText(_translate("conversionOfNumberSystems", "2"))
        self.three_Btn.setText(_translate("conversionOfNumberSystems", "3"))
        self.point_Btn.setText(_translate("conversionOfNumberSystems", "."))
        self.zero_Btn.setText(_translate("conversionOfNumberSystems", "0"))
        self.Hex.setText(_translate("conversionOfNumberSystems", "十六进制 HEX："))
        self.Dec.setText(_translate("conversionOfNumberSystems", "八进制   DEC："))
        self.Bin.setText(_translate("conversionOfNumberSystems", "二进制   BIN："))
        self.Otc.setText(_translate("conversionOfNumberSystems", "十进制   OTC："))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    win = Uiconversionofnumbersystems()
    win.show()

    sys.exit(app.exec_())
